server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 340586661148-g7n5m64e58anq9p3qtfg4sbnf5m8fvbu.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml


file:
  path: C:/junil/web-3-202210/Library-springboot-202301-junil/upload/