server:
  port: 8000

spring:
  mvc:
#    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

logging:
  level:
    me.silvernine: DEBUG

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  header: Authorization
  secret: Zaq1Xsw2Cde3Vfr4Bgt5Nhy6Mju7Ki8Lo9P0Zaq1Xsw2Cde3Vfr4Bgt5Nhy6Mju7Ki8Lo9P0Zaq1Xsw2Cde3Vfr4Bgt5Nhy6Mju7Ki8Lo9P0Zaq1Xsw2Cde3Vfr4Bgt5Nhy6Mju7Ki8Lo9P0
  token-validity-in-seconds: 86400

file:
  path: C:/junil/web-3-202210/Library-springboot-202301-junil/upload/
